### ISSUE TITLE
Device Model Anpassung hinsichtlich Altsoftware (Wartungs/Kalibrierungsintervall)

### ISSUE THREAD

**Issue by imRentable** [adamsasin95/projektstudium#29]
Bisherige Info: (3, 6, 12, 24) => Am besten Klärung mit Frontend und Anpassung an deren Gerätregistrierungsmaske.

**Comment by imRentable** [comment]
http://ceventis.de:8080/ // dierk.langbein@htw-berlin.de // dila1234 => daran orientieren!

**Comment by imRentable** [comment]
Tag muss in Label umbenannt werden.

**Comment by imRentable** [comment]
Tag muss es trotzdem geben, es handelt sich hierbei aber um ein Schild, das am Gerät klebt. Tag : Gerät => 1:1 Beziehung.

**Comment by imRentable** [comment]
Labels benötigen keine Description.

**Comment by imRentable** [comment]
Tag bzw. Label sollte auch das IEntity-Interface implementieren.

Die ganzen Models für das Identity Framework auch nicht, wär aber schon cool. Ich weiß nicht obs noch funktioniert bzgl. Tokenvergabe etc. wenn die zusätzliche Felder haben. Sollte eigentlich aber nix dagegen sprechen. Wenn du bock hast könntest das mal testen? Bei Fragen, fragen! :)

**Comment by adamsasin95** [comment]
habe änderungen in einen review-branch "model-update" gelegt,
"Tag" habe ich als property in das Device implementiert, so spart man sich die 1:1 Beziehung,
falls es noch was zu erledigen gibt dafür, kann es wieder assigned werden.

**Comment by imRentable** [comment]
Das Projekt kompiliert leider nicht. Bitte erstell auch eine entsprechende Migration für die Änderungen am Model. Das mit Tag ist super, das benötigen wir so auch.

Bzgl. "falls es noch was zu erledigen gibt dafür, kann es wieder mir assigned werden" - Es gibt noch jede Menge zu erledigen, Issues dürfen sich gern selbst assigned werden bzw. es darf sich mit dem Code und den Anforderungen auch selbst auseinandergesetzt werden und entsprechend Issues dafür selbst erstellt werden um anschließend dafür Lösungen zu implementieren. 

Nichts für ungut, aber das Ticket existierte seit 24 Tagen, dafür sind die Änderungen am Code doch recht überschaubar und das war auch dein einziges Ticket in dieser Zeitspanne.

**Comment by adamsasin95** [comment]
Alles klar, mach ich
imRentable <notifications@github.com> schrieb am So. 8. Jan. 2017 um 10:24:

**Comment by imRentable** [comment]
Habs erledigt.
